# example configuration file.
# used for testing.

$schema: config.schema.yaml
listen: 127.0.0.1:1080
algorithm:
  name: linear-scan
fallback:
  address: gcc-11.com:12345
  delay: 3000
servers:
  duck-vultr-jp1:
    address: jp1.ducksoft.example.com:1145
    method: chacha20-ietf-poly1305
    passwords:
      - 94866f9d-8f44-95cd-4541-c23495c62ccd
      - dd470899-6b11-aee7-d969-6916928709c6
  mzz-xtom-wa1:
    address: wa1.mzz.example.com:19810
    method: aes-256-gcm
    passwords:
      - aa3d43e7-c95a-e162-ed08-23b0c2e0b7d0
      - f900db69-1728-4ce4-3a87-d3eadcf604c0
